/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface TeamDiscover {
    'productid': string;
  }
  interface TeamDiscoverItem {
    'item': {
      id: number,
      name: string,
      price: number,
      images: string[]
    };
  }
}

declare global {


  interface HTMLTeamDiscoverElement extends Components.TeamDiscover, HTMLStencilElement {}
  const HTMLTeamDiscoverElement: {
    prototype: HTMLTeamDiscoverElement;
    new (): HTMLTeamDiscoverElement;
  };

  interface HTMLTeamDiscoverItemElement extends Components.TeamDiscoverItem, HTMLStencilElement {}
  const HTMLTeamDiscoverItemElement: {
    prototype: HTMLTeamDiscoverItemElement;
    new (): HTMLTeamDiscoverItemElement;
  };
  interface HTMLElementTagNameMap {
    'team-discover': HTMLTeamDiscoverElement;
    'team-discover-item': HTMLTeamDiscoverItemElement;
  }
}

declare namespace LocalJSX {
  interface TeamDiscover {
    'productid'?: string;
  }
  interface TeamDiscoverItem {
    'item'?: {
      id: number,
      name: string,
      price: number,
      images: string[]
    };
  }

  interface IntrinsicElements {
    'team-discover': TeamDiscover;
    'team-discover-item': TeamDiscoverItem;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'team-discover': LocalJSX.TeamDiscover & JSXBase.HTMLAttributes<HTMLTeamDiscoverElement>;
      'team-discover-item': LocalJSX.TeamDiscoverItem & JSXBase.HTMLAttributes<HTMLTeamDiscoverItemElement>;
    }
  }
}


