/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface TeamBasketAddBtn {
    'productid': string;
  }
  interface TeamBasketNavBasket {}
}

declare global {


  interface HTMLTeamBasketAddBtnElement extends Components.TeamBasketAddBtn, HTMLStencilElement {}
  var HTMLTeamBasketAddBtnElement: {
    prototype: HTMLTeamBasketAddBtnElement;
    new (): HTMLTeamBasketAddBtnElement;
  };

  interface HTMLTeamBasketNavBasketElement extends Components.TeamBasketNavBasket, HTMLStencilElement {}
  var HTMLTeamBasketNavBasketElement: {
    prototype: HTMLTeamBasketNavBasketElement;
    new (): HTMLTeamBasketNavBasketElement;
  };
  interface HTMLElementTagNameMap {
    'team-basket-add-btn': HTMLTeamBasketAddBtnElement;
    'team-basket-nav-basket': HTMLTeamBasketNavBasketElement;
  }
}

declare namespace LocalJSX {
  interface TeamBasketAddBtn {
    'onCounterIncrement'?: (event: CustomEvent<any>) => void;
    'productid'?: string;
  }
  interface TeamBasketNavBasket {}

  interface IntrinsicElements {
    'team-basket-add-btn': TeamBasketAddBtn;
    'team-basket-nav-basket': TeamBasketNavBasket;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'team-basket-add-btn': LocalJSX.TeamBasketAddBtn & JSXBase.HTMLAttributes<HTMLTeamBasketAddBtnElement>;
      'team-basket-nav-basket': LocalJSX.TeamBasketNavBasket & JSXBase.HTMLAttributes<HTMLTeamBasketNavBasketElement>;
    }
  }
}


