/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppBasket {}
  interface AppDetail {
    'productId': string;
  }
  interface AppHeader {}
  interface AppHome {
    'gender': string;
  }
  interface AppRoot {}
}

declare global {


  interface HTMLAppBasketElement extends Components.AppBasket, HTMLStencilElement {}
  var HTMLAppBasketElement: {
    prototype: HTMLAppBasketElement;
    new (): HTMLAppBasketElement;
  };

  interface HTMLAppDetailElement extends Components.AppDetail, HTMLStencilElement {}
  var HTMLAppDetailElement: {
    prototype: HTMLAppDetailElement;
    new (): HTMLAppDetailElement;
  };

  interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {}
  var HTMLAppHeaderElement: {
    prototype: HTMLAppHeaderElement;
    new (): HTMLAppHeaderElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-basket': HTMLAppBasketElement;
    'app-detail': HTMLAppDetailElement;
    'app-header': HTMLAppHeaderElement;
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
  }
}

declare namespace LocalJSX {
  interface AppBasket {}
  interface AppDetail {
    'productId'?: string;
  }
  interface AppHeader {}
  interface AppHome {
    'gender'?: string;
  }
  interface AppRoot {}

  interface IntrinsicElements {
    'app-basket': AppBasket;
    'app-detail': AppDetail;
    'app-header': AppHeader;
    'app-home': AppHome;
    'app-root': AppRoot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-basket': LocalJSX.AppBasket & JSXBase.HTMLAttributes<HTMLAppBasketElement>;
      'app-detail': LocalJSX.AppDetail & JSXBase.HTMLAttributes<HTMLAppDetailElement>;
      'app-header': LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
    }
  }
}


